---
# Delete instances
- name: Terminate instances that were previously launched
  ec2:
     state: "absent"
     instance_ids: "{{ item.id }}"
     region: "{{ item.region }}"
     aws_access_key: "{{ access_key }}"
     aws_secret_key: "{{ secret_key }}"
  with_items: ec2.instances

- name: Send e-mail to admins
  local_action: mail
      from={{mail_from}}
      to={{mail_to}}
      host={{mail_host}}
      subject="EC2 instance {{item.id}}"
      body="EC2 instance {{item.id}} deleted"
  when: mail_to is defined
  with_items: ec2.instances
