---
# Delete instances
- name: Terminate instances that were previously launched
  ec2:
     state: "absent"
     instance_ids: "{{ item.id }}"
     region: "{{ item.region }}"
     aws_access_key: "{{ access_key }}"
     aws_secret_key: "{{ secret_key }}"
  with_items: ec2.instances

